// flow-typed signature: 7e7df963238b3d94c4fcb47c3e94fe99
// flow-typed version: <<STUB>>/react-native-mail_v^3.0.5

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-mail'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-mail' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-mail/index' {
  declare module.exports: $Exports<'react-native-mail'>;
}
declare module 'react-native-mail/index.js' {
  declare module.exports: $Exports<'react-native-mail'>;
}
