// flow-typed signature: 214af3af1d98905d250089a280c14552
// flow-typed version: <<STUB>>/react-native-material-textfield_vgit://github.com/Airbitz/react-native-material-textfield.git

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-material-textfield'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-material-textfield' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-material-textfield/example/app' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/affix/index' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/affix/styles' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/affix/test' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/counter/index' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/counter/styles' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/counter/test' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/field/index' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/field/styles' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/field/test' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/helper/index' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/helper/styles' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/helper/test' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/label/index' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/label/test' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/line/index' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/line/styles' {
  declare module.exports: any;
}

declare module 'react-native-material-textfield/src/components/line/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-material-textfield/example/app.js' {
  declare module.exports: $Exports<'react-native-material-textfield/example/app'>;
}
declare module 'react-native-material-textfield/example/index.android.js' {
  declare module.exports: $Exports<'react-native-material-textfield/example/index.android'>;
}
declare module 'react-native-material-textfield/example/index.ios.js' {
  declare module.exports: $Exports<'react-native-material-textfield/example/index.ios'>;
}
declare module 'react-native-material-textfield/index' {
  declare module.exports: $Exports<'react-native-material-textfield'>;
}
declare module 'react-native-material-textfield/index.js' {
  declare module.exports: $Exports<'react-native-material-textfield'>;
}
declare module 'react-native-material-textfield/src/components/affix/index.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/affix/index'>;
}
declare module 'react-native-material-textfield/src/components/affix/styles.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/affix/styles'>;
}
declare module 'react-native-material-textfield/src/components/affix/test.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/affix/test'>;
}
declare module 'react-native-material-textfield/src/components/counter/index.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/counter/index'>;
}
declare module 'react-native-material-textfield/src/components/counter/styles.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/counter/styles'>;
}
declare module 'react-native-material-textfield/src/components/counter/test.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/counter/test'>;
}
declare module 'react-native-material-textfield/src/components/field/index.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/field/index'>;
}
declare module 'react-native-material-textfield/src/components/field/styles.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/field/styles'>;
}
declare module 'react-native-material-textfield/src/components/field/test.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/field/test'>;
}
declare module 'react-native-material-textfield/src/components/helper/index.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/helper/index'>;
}
declare module 'react-native-material-textfield/src/components/helper/styles.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/helper/styles'>;
}
declare module 'react-native-material-textfield/src/components/helper/test.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/helper/test'>;
}
declare module 'react-native-material-textfield/src/components/label/index.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/label/index'>;
}
declare module 'react-native-material-textfield/src/components/label/test.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/label/test'>;
}
declare module 'react-native-material-textfield/src/components/line/index.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/line/index'>;
}
declare module 'react-native-material-textfield/src/components/line/styles.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/line/styles'>;
}
declare module 'react-native-material-textfield/src/components/line/test.js' {
  declare module.exports: $Exports<'react-native-material-textfield/src/components/line/test'>;
}
