// flow-typed signature: c1a0de0f8efd758b46f249ed86771fc4
// flow-typed version: <<STUB>>/zxcvbn_v^4.4.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zxcvbn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zxcvbn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zxcvbn/dist/zxcvbn' {
  declare module.exports: any;
}

declare module 'zxcvbn/lib/adjacency_graphs' {
  declare module.exports: any;
}

declare module 'zxcvbn/lib/feedback' {
  declare module.exports: any;
}

declare module 'zxcvbn/lib/frequency_lists' {
  declare module.exports: any;
}

declare module 'zxcvbn/lib/main' {
  declare module.exports: any;
}

declare module 'zxcvbn/lib/matching' {
  declare module.exports: any;
}

declare module 'zxcvbn/lib/scoring' {
  declare module.exports: any;
}

declare module 'zxcvbn/lib/time_estimates' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zxcvbn/dist/zxcvbn.js' {
  declare module.exports: $Exports<'zxcvbn/dist/zxcvbn'>;
}
declare module 'zxcvbn/lib/adjacency_graphs.js' {
  declare module.exports: $Exports<'zxcvbn/lib/adjacency_graphs'>;
}
declare module 'zxcvbn/lib/feedback.js' {
  declare module.exports: $Exports<'zxcvbn/lib/feedback'>;
}
declare module 'zxcvbn/lib/frequency_lists.js' {
  declare module.exports: $Exports<'zxcvbn/lib/frequency_lists'>;
}
declare module 'zxcvbn/lib/main.js' {
  declare module.exports: $Exports<'zxcvbn/lib/main'>;
}
declare module 'zxcvbn/lib/matching.js' {
  declare module.exports: $Exports<'zxcvbn/lib/matching'>;
}
declare module 'zxcvbn/lib/scoring.js' {
  declare module.exports: $Exports<'zxcvbn/lib/scoring'>;
}
declare module 'zxcvbn/lib/time_estimates.js' {
  declare module.exports: $Exports<'zxcvbn/lib/time_estimates'>;
}
