export const PASSWORD_ERROR = 'Password doesn\'t meet requirements'
export const CONFIRM_PASSWORD_ERROR = 'Does not match password'
export const USERNAME_3_CHARACTERS_ERROR = 'Username must have at least 3 characters'
export const USERNAME_ASCII_ERROR = 'Username must only be ascii characters '
export const USERNAME_EXISTS_ERROR = 'Username already exists'
export const FOUR_DIGIT_PIN_ERROR = 'PIN must be four digits'
